# config.yaml
sim_duration: 10  # Seconds
num_devices: 10
arrival_rate: 20  # Base arrival rate
packet_size: 16000  # Base packet size in bits
num_resource_blocks: 5
slot_duration: 0.125  # ms
subcarriers: 12
data_rate_base: 20000000  # Base data rate in bps
priority_levels: [1, 2, 3]
max_latency: 0.001  # 1 ms
interference_rate: 1  # Bursts/s
path_loss_exponent: 3.5
noise_power: -174  # dBm/Hz
transmission_power: 23  # dBm
random_seeds: [42, 43, 44, 45, 46]
scheduling_policy: "round-robin"  # Options: preemptive, non-preemptive, round-robin, edf, fiveg-fixed, hybrid-edf 